name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */120 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run CI
      env:
          GIT_URL: ${{secrets.GIT_URL}}
          ZIPPKG_URL: ${{secrets.ZIPPKG_URL}}
      run: chmod -R 0770 init.sh && bash init.sh